version: "3"
networks:
  external:
    external: true
  internal:
services:
  rollup-fullnode:
    volumes:
       - geth-data:/mnt/docker
    depends_on:
      - geth
    networks:
      - internal
      - external
    build:
      context: packages/rollup-full-node
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      WEB3_URL: http://geth:8545/
      VOLUME_PATH: /mnt/docker
  geth:
    volumes:
       - geth-data:/mnt/docker
    networks:
      - internal
    build:
      context: docker/geth
      dockerfile: Dockerfile
    environment:
      VOLUME_PATH: /mnt/docker
volumes:
  geth-data:
